apiVersion: v1
kind: Service
metadata:
  name: addressbook-service
spec:
  selector:
    app: addressbook
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer